// @bainbridgebuilders/universal-auth | src/core/crypto-worker.ts | v1.0.1 | 2026-05-01 | BB
// Dedicated Web Worker for AES-256-GCM cryptography per §8.2.
// Lives in its own module because:
//   * Main-thread CPU should not block on Web Crypto operations
//   * Key material lives inside the worker — the CryptoKey never leaves
//     (except via structured-clone which preserves its non-exportable flag)
//
// A1 gate #3: this module asserts `typeof self.importScripts === 'function'`
// on load — it MUST be loaded in a DedicatedWorker context.
//
// v1.0.1 (B2): retired the PBKDF2 derivation path. The CryptoKey is now
// generated by the main thread via crypto.subtle.generateKey() and shipped
// into the worker as a structured-clone-safe handle. The worker is therefore
// stateless — no key cache to maintain, no derivation salts to think about.
//
// Messaging protocol:
//   main → worker: { id, op: 'encrypt' | 'decrypt', args: { key: CryptoKey, ... } }
//   worker → main: { id, result } | { id, error: string }

// ── Worker-context assertion (A1 gate #3) ────────────────────────────────

if (typeof (self as unknown as { importScripts?: unknown }).importScripts !== 'function') {
  throw new Error(
    '[@bainbridgebuilders/universal-auth] crypto-worker.ts must be loaded as a Worker, not on the main thread.'
  );
}

const AES_IV_BYTES = 12;

// ── Messaging protocol types ──────────────────────────────────────────────

interface EncryptRequest {
  id: string;
  op: 'encrypt';
  args: { plaintext: string; key: CryptoKey };
}
interface DecryptRequest {
  id: string;
  op: 'decrypt';
  args: {
    iv: Uint8Array;
    ciphertext: Uint8Array;
    key: CryptoKey;
  };
}

type WorkerRequest = EncryptRequest | DecryptRequest;

// ── Message handler ───────────────────────────────────────────────────────

self.addEventListener('message', (event: MessageEvent<WorkerRequest>) => {
  const req = event.data;
  void handleRequest(req);
});

async function handleRequest(req: WorkerRequest): Promise<void> {
  try {
    switch (req.op) {
      case 'encrypt': {
        const iv = crypto.getRandomValues(new Uint8Array(new ArrayBuffer(AES_IV_BYTES)));
        const plainBytes = new TextEncoder().encode(req.args.plaintext);
        const plainCopy = new Uint8Array(new ArrayBuffer(plainBytes.byteLength));
        plainCopy.set(plainBytes);
        const ctBuf = await crypto.subtle.encrypt(
          { name: 'AES-GCM', iv },
          req.args.key,
          plainCopy
        );
        const ciphertext = new Uint8Array(ctBuf);
        self.postMessage({ id: req.id, result: { iv, ciphertext } });
        break;
      }
      case 'decrypt': {
        // Defensive copy — transferred bytes may be detached/neutered
        const ivCopy = new Uint8Array(new ArrayBuffer(req.args.iv.byteLength));
        ivCopy.set(req.args.iv);
        const ctCopy = new Uint8Array(new ArrayBuffer(req.args.ciphertext.byteLength));
        ctCopy.set(req.args.ciphertext);
        const ptBuf = await crypto.subtle.decrypt(
          { name: 'AES-GCM', iv: ivCopy },
          req.args.key,
          ctCopy
        );
        const plaintext = new TextDecoder().decode(ptBuf);
        self.postMessage({ id: req.id, result: plaintext });
        break;
      }
      default: {
        // Unknown op — reject so the caller's Promise doesn't hang indefinitely
        const unknown = req as unknown as { id: string; op: string };
        self.postMessage({ id: unknown.id, error: `crypto-worker: unknown op "${unknown.op}"` });
        break;
      }
    }
  } catch (err) {
    self.postMessage({
      id: req.id,
      error: err instanceof Error ? err.message : 'crypto-worker unknown error',
    });
  }
}
